# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e380ded11bc0a61f9c383ec0223ce865fbca01cc760d42fffb035a40e11c5f182682116e80567af9090d00121631b816aaa62a17ad8668c5d3f55574a44d7736

test:
  secret_key_base: a08128e5d4631780fdc83ef035926d523fe73f3fa22d3a4b57b24f1d5dcce1d445f163e31f37c53ccd0159b08b111d515960b2a5e874d64d8abfa0de62f055a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
